/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Adapters.ClubAdopters;
import DAO.ClubDAO;
import DAO.IDao;
import entity.Club;
import java.awt.GraphicsEnvironment;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rym
 */
public class Iclub extends javax.swing.JFrame {

    /**
     * Creates new form Iclub
     */
    List<Club> listc;
    ClubDAO cdao=new ClubDAO();
    public Iclub() {
        initComponents();
        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
		this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
		
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1400, 725);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AdresseFiled = new javax.swing.JTextField();
        jSpinner = new javax.swing.JSpinner();
        LabelField = new javax.swing.JTextField();
        FaxField = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        VilleField = new javax.swing.JTextField();
        showbutton = new javax.swing.JButton();
        Addbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BudgetField = new javax.swing.JTextField();
        updatebutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lib = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText(" Club label:");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 130, 140, 30);

        jLabel4.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Adresse:");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 140, 30);

        jLabel5.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("Town:");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 210, 140, 30);

        jLabel6.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("Phone number:");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 130, 140, 30);

        jLabel7.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Fax number:");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 170, 140, 30);

        jLabel8.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("Number of Fields:");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 250, 140, 30);

        jLabel9.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setText("Club's budget:");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 210, 140, 30);

        AdresseFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdresseFiledActionPerformed(evt);
            }
        });
        getContentPane().add(AdresseFiled);
        AdresseFiled.setBounds(200, 170, 180, 30);

        jSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner);
        jSpinner.setBounds(200, 250, 50, 30);

        LabelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelFieldActionPerformed(evt);
            }
        });
        getContentPane().add(LabelField);
        LabelField.setBounds(200, 130, 180, 30);
        getContentPane().add(FaxField);
        FaxField.setBounds(560, 170, 180, 30);

        PhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PhoneField);
        PhoneField.setBounds(560, 130, 180, 30);
        getContentPane().add(VilleField);
        VilleField.setBounds(200, 210, 180, 30);

        showbutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        showbutton.setText("Rechercher");
        showbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(showbutton);
        showbutton.setBounds(430, 250, 90, 30);

        Addbutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Addbutton.setText("ADD");
        Addbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Addbutton);
        Addbutton.setBounds(820, 330, 90, 30);

        backbutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backbutton.setText("BACK TO MENU");
        backbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton);
        backbutton.setBounds(820, 450, 90, 30);

        deletebutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deletebutton.setText("DELETE");
        deletebutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deletebutton);
        deletebutton.setBounds(820, 370, 90, 30);

        jTable1.setModel(new ClubAdopters());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 290, 790, 210);
        getContentPane().add(BudgetField);
        BudgetField.setBounds(560, 210, 180, 30);

        updatebutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updatebutton.setText("UPDATE");
        updatebutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(updatebutton);
        updatebutton.setBounds(820, 410, 90, 30);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Club Specifications:");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 160, 30);
        getContentPane().add(lib);
        lib.setBounds(560, 250, 180, 30);

        jButton2.setText("Gestion des stades");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 30, 130, 40);

        jButton3.setText("Gestion des clubs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(110, 30, 130, 40);

        jButton1.setText("Des statistiques");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 30, 130, 40);

        jButton5.setText("Gestion des tickets");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(370, 30, 130, 40);

        jButton6.setText("Gestion des reservations");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(500, 30, 160, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backgr.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 943, 520);

        jButton4.setText("Gestion des stades");
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 30, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdresseFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdresseFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresseFiledActionPerformed

    private void LabelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelFieldActionPerformed

    private void showbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbuttonActionPerformed
        // TODO add your handling code here:
        ClubAdopters con=new ClubAdopters();
         ClubDAO dao=new ClubDAO();
         jTable1.setModel( new ClubAdopters(listc,lib.getText()));
        
    }//GEN-LAST:event_showbuttonActionPerformed

    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
        // TODO add your handling code here:
        Club c=new Club();
     IDao pdao=new ClubDAO();

            c.setLibelle_club(LabelField.getText());
            c.setAdresse_club(AdresseFiled.getText());
            c.setVille_club(VilleField.getText());
            c.setNumero_telephone(PhoneField.getText());
            c.setNumero_fax(FaxField.getText());
            c.setNbr_terrain(Integer.parseInt(jSpinner.getValue().toString()));
            c.setBudget_club(Float.parseFloat(BudgetField.getText()));
            int rep = JOptionPane.showConfirmDialog(null, "are you sure you wanna add?", "BECAREFUL", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION) {

            }
            pdao.add(c);
            JOptionPane.showMessageDialog(null, "It is added with success!");
            jTable1.setModel(new ClubAdopters());
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        Igestion c=new Igestion();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        IDao pdao=new ClubDAO();
                
                        String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
          int rep = JOptionPane.showConfirmDialog(null, "are you sure you wanna delete?", "BECAREFUL", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION) {

            }
                pdao.delete(Integer.parseInt(id));
                
                JOptionPane.showMessageDialog(null, "Deleted with success!");
   
                jTable1.setModel(new ClubAdopters());
        
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
        IDao pdao=new ClubDAO();
     Club c=new Club();
     String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
      c.setLibelle_club(LabelField.getText());
            c.setAdresse_club(AdresseFiled.getText());
            c.setVille_club(VilleField.getText());
            c.setNumero_telephone(PhoneField.getText());
            c.setNumero_fax(FaxField.getText());
            c.setNbr_terrain(Integer.parseInt(jSpinner.getValue().toString()));
            c.setBudget_club(Float.parseFloat(BudgetField.getText()));
int rep = JOptionPane.showConfirmDialog(null, "Are you sure you want to modify?", "BECAREFUL", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION) {

            }
     pdao.update(c,Integer.parseInt(id));
     
            jTable1.setModel(new ClubAdopters());
            JOptionPane.showMessageDialog(null, "UPDATED with success!");
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
       
             
        String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String libelle = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String adresse = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String ville =jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String Numero_telephone= jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        String Numero_fax = jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();
        String Nbr_terrain = jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString();
        String Budget_club = jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString();

        LabelField.setText(libelle);
        AdresseFiled.setText(adresse);
        VilleField.setText(ville);
        PhoneField.setText(Numero_telephone);
        FaxField.setText(Numero_fax);
        jSpinner.setValue(Integer.parseInt(Nbr_terrain));
        BudgetField.setText(Budget_club);
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void PhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Iclub c=new Iclub();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Istade c=new Istade();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         Iticket c=new Iticket();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Ireservation c=new Ireservation();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Istat c=new Istat();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iclub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iclub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iclub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iclub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iclub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton;
    private javax.swing.JTextField AdresseFiled;
    private javax.swing.JTextField BudgetField;
    private javax.swing.JTextField FaxField;
    private javax.swing.JTextField LabelField;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JTextField VilleField;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lib;
    private javax.swing.JButton showbutton;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
