/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Adapters.TicketAdopters;
import DAO.IDao;
import DAO.TicketDAO;
import entity.Ticket;
import java.awt.GraphicsEnvironment;
import java.sql.Connection;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import static javax.swing.UIManager.getString;
import utils.DataSource;


/**
 *
 * @author Rym
 */
public class Iticket extends javax.swing.JFrame {

    /**
     * Creates new form Iticket
     */
    TicketDAO tdao=new TicketDAO();
    Connection connection=(DataSource.getInstance()).getConnection();
        PreparedStatement pst,pst1,pst2,pst3,pst4;
        ResultSet res,res1,res2,res3,res4;
    List<Ticket> listl;
    public Iticket() {
        initComponents();
        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
		this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
		
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1400, 725);
                comboMatch();
                comboStade();
               
    }
    
        
private void comboMatch(){
        try{
String sql="select * from fttennis.matches ORDER BY `id_match` ASC";
String sql1="SELECT nom FROM joueur A INNER JOIN matches B ON A.id_joueur = B.joueur_id1_joueur";
String sql2="SELECT prenom FROM joueur A INNER JOIN matches B ON A.id_joueur = B.joueur_id1_joueur";
String sql3="SELECT nom FROM joueur A INNER JOIN matches B ON A.id_joueur = B.joueur_id2_joueur";
String sql4="SELECT prenom FROM joueur A INNER JOIN matches B ON A.id_joueur = B.joueur_id2_joueur";
        pst = connection.prepareStatement(sql);
ResultSet rs = pst.executeQuery();
 pst1 = connection.prepareStatement(sql);
ResultSet rs1 = pst.executeQuery();
 pst2 = connection.prepareStatement(sql);
ResultSet rs2= pst.executeQuery();
 pst3 = connection.prepareStatement(sql);
ResultSet rs3 = pst.executeQuery();
 pst4 = connection.prepareStatement(sql);
ResultSet rs4 = pst.executeQuery();


while( rs.next()){
if(rs.getInt("id_match")<10 && rs.getInt("id_match")>0){
    String nom1=rs1.getString("nom");
    String prenom1=rs1.getString("prenom");
    String nom2=rs2.getString("nom");
    String prenom2=rs2.getString("prenom");
String name='0'+nom1+prenom1+"vs"+nom2+prenom2;
comboBoxMatch.addItem(name); 
} 
else {
    String nom1=rs1.getString("nom");
    String prenom1=rs1.getString("prenom");
    String nom2=rs2.getString("nom");
    String prenom2=rs2.getString("prenom");
String name=nom1+prenom1+"vs"+nom2+prenom2;
comboBoxMatch.addItem(name);
} 
}
System.out.println("interfaces.Ireservation.comboMatch()");
        


}catch(Exception e){
JOptionPane.showMessageDialog(null,"erreur");
}}

private void comboStade(){
        try{
String sql="select * from fttennis.stade ORDER BY `id_stade` ASC";
pst = connection.prepareStatement(sql);
ResultSet rs = pst.executeQuery();
while( rs.next()){
if(rs.getInt("id_stade")<10 && rs.getInt("id_stade")>0){
String name= /*"0"+rs.getInt("id_joueur")+ " " +*/rs.getString("libelle_stade") ;
comboBoxStade.addItem(name); 
} 
else{String name= /*rs.getInt("id_joueur")+ " " +*/rs.getString("libelle_stade") ;
comboBoxStade.addItem(name);
} 
}
System.out.println("interfaces.Ireservation.comboStade()");
        


}catch(Exception e){
JOptionPane.showMessageDialog(null,"erreur");
}}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        retour = new javax.swing.JButton();
        Prix_Field = new javax.swing.JTextField();
        Libelle_Field = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        ajout = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lib = new javax.swing.JTextField();
        rechercher = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        comboBoxMatch = new javax.swing.JComboBox<>();
        comboBoxStade = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 0));
        jLabel3.setText("Nombre des tickets disponibles:");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 470, 230, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Libelle:");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 260, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Gestion des Tickets: ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 220, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("Prix du ticket:");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 300, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("Le match:");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 380, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 0));
        jLabel9.setText("Stade:");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 430, 120, 30);

        retour.setText("Retour vers menu");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(730, 490, 150, 30);

        Prix_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prix_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Prix_Field);
        Prix_Field.setBounds(140, 300, 230, 30);

        Libelle_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Libelle_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Libelle_Field);
        Libelle_Field.setBounds(140, 260, 230, 30);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        ajout.setText("Ajout");
        ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutActionPerformed(evt);
            }
        });
        jPanel1.add(ajout);

        delete.setText("Supprimer");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        jPanel1.add(modifier);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(680, 450, 250, 30);

        jSlider1.setMajorTickSpacing(50);
        jSlider1.setMaximum(200);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        getContentPane().add(jSlider1);
        jSlider1.setBounds(260, 470, 200, 40);

        jTable1.setModel(new TicketAdopters());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(390, 160, 540, 240);
        getContentPane().add(lib);
        lib.setBounds(520, 130, 140, 20);

        rechercher.setText("Rechercher");
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });
        getContentPane().add(rechercher);
        rechercher.setBounds(420, 130, 90, 23);

        jButton1.setText("Des statistiques");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 30, 120, 50);

        jButton2.setText("Gestion des clubs");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 30, 150, 50);

        jButton3.setText("Gestion des stades");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 30, 140, 50);

        jButton4.setText("Gestion des tickets");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(400, 30, 140, 50);

        jButton5.setText("Gestion des reservations");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(540, 30, 160, 50);

        getContentPane().add(comboBoxMatch);
        comboBoxMatch.setBounds(140, 380, 230, 30);

        getContentPane().add(comboBoxStade);
        comboBoxStade.setBounds(140, 430, 230, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tenn.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutActionPerformed
        // TODO add your handling code here:
        Ticket t=new Ticket();
     IDao pdao=new TicketDAO();

            t.setLibelle_ticket(Libelle_Field.getText());
            t.setPrix_ticket(Float.parseFloat(Prix_Field.getText()));
            t.setMatch_id_match(Integer.parseInt(comboBoxMatch.getSelectedItem().toString().substring(0,2)));
            t.setStade_id_stade(Integer.parseInt(comboBoxStade.getSelectedItem().toString().substring(0,2)));
            t.setNbr_ticket_dispo(jSlider1.getValue());

            int rep = JOptionPane.showConfirmDialog(null, "are you sure you wanna add?", "BECAREFUL", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION) {

            }
            pdao.add(t);
            JOptionPane.showMessageDialog(null, "It is added with success!");
            jTable1.setModel(new TicketAdopters());
    }//GEN-LAST:event_ajoutActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         IDao pdao=new TicketDAO();
                
                        String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
          int rep = JOptionPane.showConfirmDialog(null, "are you sure you wanna delete?", "BECAREFUL", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION) {

            }
                pdao.delete(Integer.parseInt(id));
                
                JOptionPane.showMessageDialog(null, "Deleted with success!");
   
                jTable1.setModel(new TicketAdopters());
        
    }//GEN-LAST:event_deleteActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
         IDao pdao=new TicketDAO();
     Ticket t=new Ticket();
     String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            t.setLibelle_ticket(Libelle_Field.getText());
            t.setPrix_ticket(Float.parseFloat(Prix_Field.getText()));
            t.setMatch_id_match(Integer.parseInt(comboBoxMatch.getSelectedItem().toString().substring(0,2)));
            t.setStade_id_stade(Integer.parseInt(comboBoxStade.getSelectedItem().toString().substring(0,2)));
            t.setNbr_ticket_dispo(jSlider1.getValue());
int rep = JOptionPane.showConfirmDialog(null, "Are you sure you want to modify?", "BECAREFUL", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION) {

            }
     pdao.update(t,Integer.parseInt(id));
     
            jTable1.setModel(new TicketAdopters());
            JOptionPane.showMessageDialog(null, "UPDATED with success!");
    }//GEN-LAST:event_modifierActionPerformed

    private void Prix_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prix_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Prix_FieldActionPerformed

    private void Libelle_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Libelle_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Libelle_FieldActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        // TODO add your handling code here:
        Igestion c=new Igestion();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_retourActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String libelle = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String prix = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String lib_match= jTable1.getValueAt(jTable1.getSelectedRow(),4).toString();
        String stade = jTable1.getValueAt(jTable1.getSelectedRow(),5).toString();
        String nbr_ticket_dispo = jTable1.getValueAt(jTable1.getSelectedRow(),8).toString();
        

        Libelle_Field.setText(libelle);
        Prix_Field.setText(prix);
       Integer.parseInt(comboBoxMatch.getSelectedItem().toString().substring(0,2));
       Integer.parseInt(comboBoxStade.getSelectedItem().toString().substring(0,2));
        jSlider1.setValue(Integer.parseInt(nbr_ticket_dispo));
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        // TODO add your handling code here:
        TicketAdopters con=new TicketAdopters();
         TicketDAO dao=new TicketDAO();
         jTable1.setModel( new TicketAdopters(listl,lib.getText()));
    }//GEN-LAST:event_rechercherActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Istade c=new Istade();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Iticket c=new Iticket();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Iclub c=new Iclub();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Ireservation c=new Ireservation();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Istat c=new Istat();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Libelle_Field;
    private javax.swing.JTextField Prix_Field;
    private javax.swing.JButton ajout;
    private javax.swing.JComboBox<String> comboBoxMatch;
    private javax.swing.JComboBox<String> comboBoxStade;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lib;
    private javax.swing.JButton modifier;
    private javax.swing.JButton rechercher;
    private javax.swing.JButton retour;
    // End of variables declaration//GEN-END:variables
}
